import { sql } from "drizzle-orm"
import { timestamp, uuid, varchar } from "drizzle-orm/pg-core"

/* ============================================================================
 * Column helpers reused by every table.
 * ========================================================================== */

/**
 * UUIDv7 primary key, generated by the database.
 *
 * v7 rather than v4 because it is time-ordered: inserts land at the end of the
 * index instead of scattering across it, which keeps write amplification down
 * as a table grows. Postgres 18 ships `uuidv7()` natively, so the application
 * never has to mint one.
 */
export const primaryId = () =>
  uuid("id")
    .primaryKey()
    .default(sql`uuidv7()`)

export const timestamps = {
  createdAt: timestamp("created_at", { withTimezone: true, mode: "string" })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "string" })
    .notNull()
    .defaultNow(),
}

/**
 * An enum column: `varchar` plus a `CHECK`, never a native Postgres enum.
 *
 * `ALTER TYPE … ADD VALUE` cannot run inside a transaction and a value can
 * never be removed. This product dropped `checked_out` and added `no_show`
 * before a line of SQL was written, so the sets will keep moving — and here a
 * change is `DROP CONSTRAINT` / `ADD CONSTRAINT`, which is transactional and
 * reversible.
 *
 * The matching CHECK is declared per table alongside the column, so the values
 * and the constraint sit where they can be read together. See
 * docs/ARCHITECTURE.md §1.2.
 */
export const enumColumn = (name: string, length = 32) => varchar(name, { length })
