/**
 * Drizzle schema — the canonical Stayora data model.
 *
 * Tables arrive module by module. Every one of them encodes decisions from
 * `docs/BUSINESS-RULES.md`; read that before adding a column.
 *
 * Conventions (docs/ARCHITECTURE.md §1):
 *  - money is `integer` CENTS, never a float
 *  - enums are `varchar` + `CHECK`, never native Postgres enums
 *  - primary keys are UUIDv7, generated by the database
 *  - every table carries `created_at` / `updated_at`
 */

export * from "./auth"
export * from "./catalog"
export * from "./inventory"
export * from "./promotions"
export * from "./bookings"
export * from "./reviews"
export * from "./payments"
export * from "./finance"
export * from "./notifications"
export * from "./analytics"
export * from "./audit"
export * from "./support"
export * from "./contracts"
export * from "./registration"
export * from "./platform"
export * from "./rate-limits"
