import {
  Activity,
  AlertTriangle,
  ArrowRight,
  ArrowUpRight,
  BadgeCheck,
  BarChart3,
  BedDouble,
  Bell,
  Building2,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarPlus,
  CalendarRange,
  Camera,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  Circle,
  Clock,
  CreditCard,
  DollarSign,
  Download,
  FileText,
  Filter,
  Globe,
  Hotel,
  Inbox,
  Languages,
  LayoutDashboard,
  Lightbulb,
  LogIn,
  LogOut,
  Mail,
  MapPin,
  MessageSquare,
  MoreVertical,
  Percent,
  Phone,
  Plus,
  Search,
  Send,
  Settings,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Star,
  Tag,
  TrendingDown,
  TrendingUp,
  User,
  Users,
  Wallet,
  Wifi,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react"

import { cn } from "@/lib/utils"

/**
 * Curated lucide map. Data files carry icon *names* (strings); components
 * resolve them through here. Unknown names fall back to a neutral dot so a
 * typo never crashes a page. (lucide-react is v1 — no brand icons exist.)
 */
const iconMap: Record<string, LucideIcon> = {
  Activity,
  AlertTriangle,
  ArrowRight,
  ArrowUpRight,
  BadgeCheck,
  BarChart3,
  BedDouble,
  Bell,
  Building2,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarPlus,
  CalendarRange,
  Camera,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  Circle,
  Clock,
  CreditCard,
  DollarSign,
  Download,
  FileText,
  Filter,
  Globe,
  Hotel,
  Inbox,
  Languages,
  LayoutDashboard,
  Lightbulb,
  LogIn,
  LogOut,
  Mail,
  MapPin,
  MessageSquare,
  MoreVertical,
  Percent,
  Phone,
  Plus,
  Search,
  Send,
  Settings,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Star,
  Tag,
  TrendingDown,
  TrendingUp,
  User,
  Users,
  Wallet,
  Wifi,
  Wrench,
  X,
  Zap,
}

export function Icon({
  name,
  className,
}: {
  name?: string
  className?: string
}) {
  const Cmp = (name && iconMap[name]) || Circle
  return <Cmp className={cn("size-4", className)} />
}

export function getIcon(name?: string): LucideIcon {
  return (name && iconMap[name]) || Circle
}
